config/routes.rb
Rails.application.routes.draw do
	
	root :to => 'home#index'
	
	get 'about' => 'home#about'
	get 'contact' => 'home#contact'
	get 'terms' => 'home#terms'
	get 'privacy' => 'home#privacy'
	get 'admin' => 'home#admin'
	get 'show_all_categories' => 'home#show_all_categories'
	get 'blog' => 'home#blog'
	get 'pro' => 'home#pro'
	get 'recent_newsletters' => 'home#recent_newsletters'
	get 'newsletter/latest/:name' => 'newsletters#latest', as: :latest_newsletter
	get 'newsletter/list(/:name)' => 'newsletters#list', as: :newsletter_list
	get 'newsletter/:id' => 'newsletters#show',  as: :newsletter
	get 'newsletter' => 'newsletters#new'
	get 'newsletters' => 'newsletters#new'
	get 'newsletters/subscribed' => 'newsletters#subscribed'
	post 'newsletters/subscribe' => 'newsletters#subscribe'
	get 'oldnewsletters' => 'newsletters#new', oldnewsletters: true
	get 'kidnote' => 'newsletters#new', alerts: true
	get 'kidnotes' => 'newsletters#new', alerts: true, as: :alerts
	get 'kidnotes/subscribed' => 'newsletters#subscribed', alerts: true, as: :alerts_subscribed
	post 'kidnotes/subscribe' => 'newsletters#subscribe', alerts: true, as: :alerts_subscribe
	
	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions', 
		confirmations: 'users/confirmations',
		two_factor_authentication: 'users/two_factor_authentication',
		omniauth_callbacks: 'omniauth_callbacks'
	}
	
	devise_scope :user do
		get '/provider/sign_up', to: 'users/registrations#new', is_provider: true
		get '/member/sign_up', to: 'users/registrations#new', is_provider: false
		get '/member/sign_up_return', to: 'users/registrations#new', is_provider: false, store_referrer: true
		get '/member/awaiting_confirmation', to: 'users/registrations#awaiting_confirmation'
		get '/member/sign_in_return', to: 'devise/sessions#new', store_referrer: true
		get '/alpha/sign_up', to: 'users/registrations#new', is_private_alpha: true
		get '/newsletter', to: 'users/registrations#new', nlsub: 't', as: :newsletter_signup
		get '/newsletters', to: 'users/registrations#new', nlsub: 't'
		get '/in_blog/sign_up', to: 'users/registrations#new', blog: true, nlsub: true, in_blog: true
		get '/in_blog/awaiting_confirmation', to: 'users/registrations#in_blog_awaiting_confirmation', in_blog: true
		get '/in_blog/edit_subscriptions', to: 'users/registrations#in_blog_edit_subscriptions', in_blog: true
		get 'two_factor_authentication/qrcode', to: 'users/two_factor_authentication#qrcode'
		get 'two_factor_authentication/reset_code', to: 'users/two_factor_authentication#reset_code'
	end
	
	get 'edit_subscriptions' => 'users#edit_subscriptions', as: 'edit_subscriptions'
	patch 'update_subscriptions' => 'users#update_subscriptions'
	
	
	get 'claim_profile/:token' => 'users#claim_profile', as: :claim_user_profile
	get 'claim_profile/:token/confirm' => 'users#force_claim_profile', as: :force_claim_user_profile
	
	resources :users, only: [:index, :show] do
		member do
			patch 'update_profile_help'
			patch 'formlet_update'
		end
	end
	
	resources :profiles do
		member do
			get 'new_invitation'
			patch 'send_invitation'
			get 'rating_score'
			get 'edit_rating'
			get 'rate'
			post 'rate'
			patch 'formlet_update'
			post 'photo_update'
			get 'show_plain'
			get 'edit_plain'
			get 'claim/:token', action: :show_claiming, as: :show_claiming
			get 'services_info'
			get 'show_tab'
			get 'edit_tab'
			get 'about_payments'
		end
		collection do
			get :admin
			get 'page/:page', action: :index
			get :autocomplete_service_name
			get :autocomplete_specialty_name
			get :autocomplete_location_city
			get :autocomplete_profile_lead_generator
			get :no_categories
			get :no_subcategories
			get :no_services
			get :location_country_data
		end
	end
	
	get 'my_profile' => 'profiles#view_my_profile'
	get 'confirm_claim_profile/:claim_token' => 'profiles#view_my_profile', as: :confirm_claim_profile
	get 'edit_my_profile' => 'profiles#edit_my_profile'
	
	get 'providers' => 'profiles#link_index'
	get 'providers/page/:page' => 'profiles#link_index'
	
	get 'search_providers' => 'profiles#search'
	get 'search_providers/service/:service_id' => 'profiles#search', as: :search_providers_by_service
	get 'search_providers/service/:service_id/page/:page' => 'profiles#search'
	
	resources :categories, except: :show do
		member do
			patch :add_subcategory
			patch :update_subcategory
			patch :remove_subcategory
		end
		collection do
			get :autocomplete_subcategory_name
		end
	end
	
	resources :subcategories, except: :show do
		member do
			patch :add_service
			patch :update_service
			patch :remove_service
		end
		collection do
			get :find_by_name
			get :autocomplete_service_name
		end
	end
	
	resources :services, except: :show do
		get :find_by_name, on: :collection
	end
	
	resources :specialties, except: :show do
		collection do
			get :find_by_name
			get :autocomplete_search_term_name
		end
	end
	
	resources :reviews, except: [:new, :index] do
		member do
			patch :admin_update
		end
		collection do
			post :admin_create
		end
	end
	get 'review/:profile_id' => 'reviews#new', as: :new_review_for_profile
	post 'review/:profile_id'     => 'reviews#create', as: :save_review_for_profile
	
	resources :provider_suggestions

	resources :profile_claims
	get 'profile_claim/:profile_id' => 'profile_claims#new', as: :new_claim_for_profile
	
	resources :contact_blockers
	get 'noemail/:email_delivery_token' => 'contact_blockers#new_from_email_delivery', as: :new_contact_blocker_from_email_delivery
	post 'noemail/:email_delivery_token' => 'contact_blockers#create_from_email_delivery', as: :create_contact_blocker_from_email_delivery
	get 'noemailerror' => 'contact_blockers#email_delivery_not_found', as: :email_delivery_not_found
	get 'noemailconfirmation' => 'contact_blockers#contact_blocker_confirmation', as: :contact_blocker_confirmation
	get 'optout' => 'contact_blockers#new_from_email_address', as: :new_contact_blocker_from_email_address
	post 'optout' => 'contact_blockers#create_from_email_address', as: :create_contact_blocker_from_email_address
	patch 'optout' => 'contact_blockers#create_from_email_address'
	
	post 'magenta/:provider_id' => 'stripe#webhook'
	mount StripeEvent::Engine => '/cyan'

	match 'hooks/a11d83adba52b483798f5e7de90c3e57' => 'mailchimp_webhook#process_notification', via: [:get, :post]

	resources :customers
	get 'authorize_payment/:profile_id' => 'customers#authorize_payment', as: :authorize_payment
	get 'authorize_payment_confirmation/:profile_id' => 'customers#authorize_payment_confirmation', as: :authorize_payment_confirmation
	resources :customer_files, only: [:index, :show] do
		member do
			get :new_charge
			patch :create_charge
		end
	end
	
	resources :stripe_charges, only: :show do
		member do
			patch :create_refund
			get :show_to_client
		end
	end
	
	resources :story_teasers do
		member do
			patch :activate
			patch :deactivate
		end
	end
	
	resources :email_deliveries do
		collection do
			get :new_list
			post :create_list
		end
	end
	
	match '*undefined_path' => 'application#not_found', via: :all
	

end

app/models/service.rb
class Service < ActiveRecord::Base
	has_paper_trail # Track changes to each service.
	
	DEFAULT_ACCESSIBLE_ATTRIBUTES = [ :name, :is_predefined, :specialty_ids, :display_order, :show_on_home_page ]
	
	# Strip leading and trailing whitespace from (admin) input intended for these attributes.
	auto_strip_attributes :name
	
	has_and_belongs_to_many :profiles
	
	has_and_belongs_to_many :categories
	
	has_many :service_subcategories
	has_many :subcategories, through: :service_subcategories
	
	has_and_belongs_to_many :specialties
	
	default_scope { where(trash: false) }
	scope :trash, -> { rewhere(trash: true) }
	scope :belongs_to_a_subcategory, -> { joins(:subcategories).order('lower(services.name)') } # may contain duplicates
	scope :predefined, -> { where(is_predefined: true) }
	scope :order_by_name, -> { order('lower(name)') }
	scope :display_order, -> { order(:display_order) }
	scope :for_home_page, -> { where(show_on_home_page: true) }
	
	MAX_STRING_LENGTH = 254
	
	validates :name, presence: true
	validates :name, length: {maximum: MAX_STRING_LENGTH}
	validates :display_order, numericality: {only_integer: true}, allow_nil: true
	
	after_save :notify_subcategories
	
	paginates_per 20 # Default number shown per page in index listing.
	
	include CachingForModel
	predefined_info_parent :category
	
	include SunspotIndexing
	
	def browsable?
		subcategories.any? &:browsable?
	end
	
	# Specialties that are eligible to be assigned to this service.
	# Includes specialties that are already assigned even if they are not predefined.
	def assignable_specialties
		(Specialty.predefined + specialties).sort_by(&:lower_case_name).uniq
	end
	
	private
	
	def notify_subcategories
		subcategories.each { |subcategory| subcategory.services_changed self }
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	layout 'plain'
	
	before_action :authenticate_user!
	
	# @service and @services initialized by load_and_authorize_resource with cancan ability conditions.
	load_and_authorize_resource
	
	def index
		@services = @services.order_by_name.page(params[:page]).per(params[:per_page])
	end
	
	def new
		@service.is_predefined = true
	end
	
	def create
		if @service.save
			set_flash_message :notice, :created, name: @service.name
			redirect_to edit_service_path(@service)
		else
			set_flash_message :alert, :create_error
			render action: :new
		end
	end
	
	def update
		if @service.update_attributes(service_params)
			if (subcategory_id = params[:subcategory_id]).present?
				# We came from a mini-form on a subcategory admin page.
				redirect_to edit_subcategory_path(subcategory_id, anchor: 'links')
			else
				set_flash_message :notice, :updated, name: @service.name
				redirect_to edit_service_path(@service)
			end
		else
			set_flash_message :alert, :update_error
			render action: :edit
		end
	end
	
	def destroy
		@service.trash = true
		if @service.save
			set_flash_message :notice, :destroyed, name: @service.name
			redirect_to services_url
		else
			set_flash_message :alert, :destroy_error
			render action: :edit
		end
	end
	
	def find_by_name
		name = params[:name]
		if name.present? && (service = Service.find_by_name name)
			redirect_to edit_service_path(service)
		else
			set_flash_message :alert, :not_found_by_name, name: name
			redirect_to services_url
		end
	end
	
	private
	
	# Use this method to whitelist the permissible parameters. Example:
	# params.require(:person).permit(:name, :age)
	# Also, you can specialize this method with per-user checking of permissible attributes.
	def service_params
		params.require(:service).permit(*Service::DEFAULT_ACCESSIBLE_ATTRIBUTES)
	end
end

app/views/services/_edit_form.html.haml
= simple_form_for @service do |f|
	= f.input :name do
		= f.autocomplete_field :name, autocomplete_service_name_profiles_path, size: 50
	-# = f.input :is_predefined
	-# = f.input :show_on_home_page
	-# = f.input :display_order, hint: t('views.service.edit.display_order_hint'), input_html: {size: 4}
	-# = f.association :specialties, as: :check_boxes, collection: @service.assignable_specialties
	= f.button :submit
	= link_to t('views.cancel'), services_path

app/views/services/edit.html.haml
- @page_title = "#{company_name} - Edit service '#{@service.name}'"
.edit
	%h1= "Edit service '#{@service.name}'"
	#top_bar
		= render partial: 'home/admin_nav'
	#forms
		= render partial: 'edit_form'
		- if can?(:destroy, @service)
			= form_for @service, method: :delete, html: {id: 'destroy_service', class: 'destroy_button'} do |f|
				= f.submit t('views.service.edit.destroy_button'), data: { disable_with: t('views.category.edit.destroy_button_disable'), confirm: t('views.service.edit.destroy_confirm') }
	#links
		%a{name: 'links'}
		%h1= Service.human_attribute_name :subcategories
		%ul
			- if @service.subcategories.present?
				- @service.subcategories.order_by_name.each do |record|
					%li= link_to record.name, edit_subcategory_path(record), class: 'name'
			- else
				%li= link_to t('views.service.edit.add_subcategories'), subcategories_path
		-# %h1= Service.human_attribute_name :specialties
		-# %table
		-# 	%thead
		-# 		%tr
		-# 			%th.miniform_header
		-# 				&nbsp;&nbsp;&nbsp;&nbsp;
		-# 				= t 'views.specialty.name'
		-# 			%th Edit
		-# 	%tbody
		-# 		- @service.specialties.order_by_name.each do |record|
		-# 			%tr
		-# 				%td.miniform
		-# 					= form_for record do |f|
		-# 						= f.submit 'Save', data: { disable_with: 'Save' }
		-# 						= f.text_field :name, size: 30
		-# 						= hidden_field_tag :service_id, @service.id
		-# 				%td= link_to record.name, edit_specialty_path(record), class: 'name'
= render partial: 'shared/save_changes_prompt'

app/views/services/index.html.haml
- @page_title = "#{company_name} - #{t('views.service.name').pluralize}"
.index
	%h1= t('views.service.name').pluralize
	#top_bar
		= render partial: 'home/admin_nav'
	.list{align: 'center'}
		= form_tag find_by_name_services_path, method: :get do
			= submit_tag t('views.find_button'), data: { disable_with: 'Finding...' }
			= autocomplete_form_field 'name', '', autocomplete_service_name_profiles_path, placeholder: t('views.service.view.find_by_name'), size: 50
		.pagination_nav
			= render partial: 'shared/per_page_form', locals: { record_type: Service }
			= paginate @services
		%table
			%thead
				%tr
					%th
						= t 'views.service.name'
					-# 	%br
					-# 	= t 'views.not_browsable'
					-# %th.large= Service.human_attribute_name(:specialties)
					-# %th= Service.human_attribute_name(:is_predefined)
					-# %th= Service.human_attribute_name(:show_on_home_page)
					-# %th= Service.human_attribute_name(:display_order)
					%th.large= Service.human_attribute_name(:subcategories)
			%tbody
				- @services.each do |service|
					%tr
						%td= link_to service.name, edit_service_path(service), class: "#{service.browsable? ? 'browsable' : 'not_browsable'}"
						-# %td
						-# 	- service.specialties.order_by_name.each do |record|
						-# 		= link_to record.name, edit_specialty_path(record), class: "name #{record.browsable? ? 'browsable' : 'not_browsable'}"
						-# %td{class: "#{service.is_predefined ? 'predefined' : 'not_predefined'}"}= service.is_predefined
						-# %td= service.show_on_home_page ? t('views.service.view.show_on_home_page') : t('views.service.view.do_not_show_on_home_page')
						-# %td= service.display_order
						%td
							- service.subcategories.order_by_name.each do |record|
								= link_to record.name, edit_subcategory_path(record), class: "name #{record.browsable? ? 'browsable' : 'not_browsable'}"
		.pagination_nav
			= render partial: 'shared/per_page_form', locals: { record_type: Service }
			= paginate @services

app/views/services/new.html.haml
- @page_title = "#{company_name} - #{t('views.service.edit.create')}"
.edit
	%h1= t('views.service.edit.create')
	#top_bar
		= render partial: 'home/admin_nav'
	#forms
		= render partial: 'edit_form'
= render partial: 'shared/save_changes_prompt'