config/routes.rb
Rails.application.routes.draw do
	
	root :to => 'home#index'
	
	get 'about' => 'home#about'
	get 'contact' => 'home#contact'
	get 'terms' => 'home#terms'
	get 'privacy' => 'home#privacy'
	get 'admin' => 'home#admin'
	get 'show_all_categories' => 'home#show_all_categories'
	get 'blog' => 'home#blog'
	get 'pro' => 'home#pro'
	get 'recent_newsletters' => 'home#recent_newsletters'
	get 'newsletter/latest/:name' => 'newsletters#latest', as: :latest_newsletter
	get 'newsletter/list(/:name)' => 'newsletters#list', as: :newsletter_list
	get 'newsletter/:id' => 'newsletters#show',  as: :newsletter
	get 'newsletter' => 'newsletters#new'
	get 'newsletters' => 'newsletters#new'
	get 'newsletters/subscribed' => 'newsletters#subscribed'
	post 'newsletters/subscribe' => 'newsletters#subscribe'
	get 'oldnewsletters' => 'newsletters#new', oldnewsletters: true
	get 'kidnote' => 'newsletters#new', alerts: true
	get 'kidnotes' => 'newsletters#new', alerts: true, as: :alerts
	get 'kidnotes/subscribed' => 'newsletters#subscribed', alerts: true, as: :alerts_subscribed
	post 'kidnotes/subscribe' => 'newsletters#subscribe', alerts: true, as: :alerts_subscribe
	
	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions', 
		confirmations: 'users/confirmations',
		two_factor_authentication: 'users/two_factor_authentication',
		omniauth_callbacks: 'omniauth_callbacks'
	}
	
	devise_scope :user do
		get '/provider/sign_up', to: 'users/registrations#new', is_provider: true
		get '/member/sign_up', to: 'users/registrations#new', is_provider: false
		get '/member/sign_up_return', to: 'users/registrations#new', is_provider: false, store_referrer: true
		get '/member/awaiting_confirmation', to: 'users/registrations#awaiting_confirmation'
		get '/member/sign_in_return', to: 'devise/sessions#new', store_referrer: true
		get '/alpha/sign_up', to: 'users/registrations#new', is_private_alpha: true
		get '/newsletter', to: 'users/registrations#new', nlsub: 't', as: :newsletter_signup
		get '/newsletters', to: 'users/registrations#new', nlsub: 't'
		get '/in_blog/sign_up', to: 'users/registrations#new', blog: true, nlsub: true, in_blog: true
		get '/in_blog/awaiting_confirmation', to: 'users/registrations#in_blog_awaiting_confirmation', in_blog: true
		get '/in_blog/edit_subscriptions', to: 'users/registrations#in_blog_edit_subscriptions', in_blog: true
		get 'two_factor_authentication/qrcode', to: 'users/two_factor_authentication#qrcode'
		get 'two_factor_authentication/reset_code', to: 'users/two_factor_authentication#reset_code'
	end
	
	get 'edit_subscriptions' => 'users#edit_subscriptions', as: 'edit_subscriptions'
	patch 'update_subscriptions' => 'users#update_subscriptions'
	
	
	get 'claim_profile/:token' => 'users#claim_profile', as: :claim_user_profile
	get 'claim_profile/:token/confirm' => 'users#force_claim_profile', as: :force_claim_user_profile
	
	resources :users, only: [:index, :show] do
		member do
			patch 'update_profile_help'
			patch 'formlet_update'
		end
	end
	
	resources :profiles do
		member do
			get 'new_invitation'
			patch 'send_invitation'
			get 'rating_score'
			get 'edit_rating'
			get 'rate'
			post 'rate'
			patch 'formlet_update'
			post 'photo_update'
			get 'show_plain'
			get 'edit_plain'
			get 'claim/:token', action: :show_claiming, as: :show_claiming
			get 'services_info'
			get 'show_tab'
			get 'edit_tab'
			get 'about_payments'
		end
		collection do
			get :admin
			get 'page/:page', action: :index
			get :autocomplete_service_name
			get :autocomplete_specialty_name
			get :autocomplete_location_city
			get :autocomplete_profile_lead_generator
			get :no_categories
			get :no_subcategories
			get :no_services
			get :location_country_data
		end
	end
	
	get 'my_profile' => 'profiles#view_my_profile'
	get 'confirm_claim_profile/:claim_token' => 'profiles#view_my_profile', as: :confirm_claim_profile
	get 'edit_my_profile' => 'profiles#edit_my_profile'
	
	get 'providers' => 'profiles#link_index'
	get 'providers/page/:page' => 'profiles#link_index'
	
	get 'search_providers' => 'profiles#search'
	get 'search_providers/service/:service_id' => 'profiles#search', as: :search_providers_by_service
	get 'search_providers/service/:service_id/page/:page' => 'profiles#search'
	
	resources :categories, except: :show do
		member do
			patch :add_subcategory
			patch :update_subcategory
			patch :remove_subcategory
		end
		collection do
			get :autocomplete_subcategory_name
		end
	end
	
	resources :subcategories, except: :show do
		member do
			patch :add_service
			patch :update_service
			patch :remove_service
		end
		collection do
			get :find_by_name
			get :autocomplete_service_name
		end
	end
	
	resources :services, except: :show do
		get :find_by_name, on: :collection
	end
	
	resources :specialties, except: :show do
		collection do
			get :find_by_name
			get :autocomplete_search_term_name
		end
	end
	
	resources :reviews, except: [:new, :index] do
		member do
			patch :admin_update
		end
		collection do
			post :admin_create
		end
	end
	get 'review/:profile_id' => 'reviews#new', as: :new_review_for_profile
	post 'review/:profile_id'     => 'reviews#create', as: :save_review_for_profile
	
	resources :provider_suggestions

	resources :profile_claims
	get 'profile_claim/:profile_id' => 'profile_claims#new', as: :new_claim_for_profile
	
	resources :contact_blockers
	get 'noemail/:email_delivery_token' => 'contact_blockers#new_from_email_delivery', as: :new_contact_blocker_from_email_delivery
	post 'noemail/:email_delivery_token' => 'contact_blockers#create_from_email_delivery', as: :create_contact_blocker_from_email_delivery
	get 'noemailerror' => 'contact_blockers#email_delivery_not_found', as: :email_delivery_not_found
	get 'noemailconfirmation' => 'contact_blockers#contact_blocker_confirmation', as: :contact_blocker_confirmation
	get 'optout' => 'contact_blockers#new_from_email_address', as: :new_contact_blocker_from_email_address
	post 'optout' => 'contact_blockers#create_from_email_address', as: :create_contact_blocker_from_email_address
	patch 'optout' => 'contact_blockers#create_from_email_address'
	
	post 'magenta/:provider_id' => 'stripe#webhook'
	mount StripeEvent::Engine => '/cyan'

	match 'hooks/a11d83adba52b483798f5e7de90c3e57' => 'mailchimp_webhook#process_notification', via: [:get, :post]

	resources :customers
	get 'authorize_payment/:profile_id' => 'customers#authorize_payment', as: :authorize_payment
	get 'authorize_payment_confirmation/:profile_id' => 'customers#authorize_payment_confirmation', as: :authorize_payment_confirmation
	resources :customer_files, only: [:index, :show] do
		member do
			get :new_charge
			patch :create_charge
		end
	end
	
	resources :stripe_charges, only: :show do
		member do
			patch :create_refund
			get :show_to_client
		end
	end
	
	resources :story_teasers do
		member do
			patch :activate
			patch :deactivate
		end
	end
	
	resources :email_deliveries do
		collection do
			get :new_list
			post :create_list
		end
	end
	
	match '*undefined_path' => 'application#not_found', via: :all
	

end

app/models/email_delivery.rb
class EmailDelivery < ActiveRecord::Base
	has_paper_trail # Track changes to each email delivery record.
	
	DEFAULT_ACCESSIBLE_ATTRIBUTES = [:recipient, :sender, :email_type, :tracking_category]
	
	# Strip leading and trailing whitespace from input intended for these attributes.
	auto_strip_attributes :recipient, :sender, :email_type, :tracking_category
	
	belongs_to :profile
	
	validates :recipient, email: true
	
	has_many :contact_blockers
	
	scope :order_by_descending_id, -> { order('id DESC') }
	
	# Generate a unique token.
	def self.generate_token
		UUIDTools::UUID.timestamp_create.to_s
	end
end

app/controllers/email_deliveries_controller.rb
class EmailDeliveriesController < ApplicationController
	layout 'plain'
	
	before_action :authenticate_user!
	
	# @email_delivery and @email_deliveries initialized by load_and_authorize_resource with cancan ability conditions.
	load_and_authorize_resource
	skip_load_resource only: [:new_list, :create_list, :show_list]

	def index
		@order_by_options = { sender: 'sender', recipient: 'recipient', email_type: 'email type', recent: 'recent first' }
		@email_deliveries = case params[:order_by]
		when 'sender'
			@email_deliveries.order(:sender).order_by_descending_id
		when 'recipient'
			@email_deliveries.order(:recipient).order_by_descending_id
		when 'email_type'
			@email_deliveries.order(:email_type).order_by_descending_id
		when 'recent'
			@email_deliveries.order_by_descending_id
		else
			@email_deliveries.order_by_descending_id
		end.page(params[:page]).per(params[:per_page])
	end

	def new
		@email_delivery.sender = EmailDelivery.order_by_descending_id.first.try(:sender)
		@email_delivery.email_type = 'provider_sell'
	end
	
	def create
		@email_delivery.token ||= EmailDelivery.generate_token
		if @email_delivery.save
			set_flash_message :notice, :created, recipient: @email_delivery.recipient
			redirect_to email_delivery_path(@email_delivery)
		else
			set_flash_message :alert, :create_error
			render action: :new
		end
	end

	def new_list
		@sender = EmailDelivery.order_by_descending_id.first.try(:sender)
		@email_type = 'provider_sell'
	end
	
	def create_list
		@sender = params[:sender]
		@email_type = params[:email_type]
		@email_list = params[:email_list]
		@create_list = CreatePermittedEmailDeliveryList.new({
			sender: @sender,
			email_type: @email_type,
			email_list: @email_list
		})
		if @create_list.call
			@email_unsubscribe_list = @create_list.email_unsubscribe_list_string
			@blocked_recipients = @create_list.blocked_recipients.join("\n")
			@notice = t('controllers.email_deliveries.created_list') if @create_list.email_deliveries.present?
			render action: :show_list
		else
			@alert = t('controllers.email_deliveries.create_list_error', message: @create_list.errors.uniq.join('; '))
			@create_list.destroy
			render action: :new_list
		end
	end

	# def edit
	# end
	
	def update
		if @email_delivery.update_attributes(email_delivery_params)
			set_flash_message :notice, :updated, recipient: @email_delivery.recipient
			redirect_to email_delivery_path(@email_delivery)
		else
			set_flash_message :alert, :update_error
			render action: :edit
		end
	end
	
	def destroy
		if @email_delivery.destroy
			set_flash_message :notice, :destroyed, recipient: @email_delivery.recipient
			redirect_to email_deliveries_url
		else
			set_flash_message :alert, :destroy_error
			render action: :edit
		end
	end
	
	private
	
	# Use this method to whitelist the permissible parameters. Example:
	# params.require(:person).permit(:name, :age)
	# Also, you can specialize this method with per-user checking of permissible attributes.
	def email_delivery_params
		params.require(:email_delivery).permit(*EmailDelivery::DEFAULT_ACCESSIBLE_ATTRIBUTES)
	end
end

app/helpers/email_deliveries_helper.rb
module EmailDeliveriesHelper
	
	def generic_email_delivery_info(delivery)
		t 'views.email_delivery.view.info', recipient: delivery.recipient, time: display_profile_time(delivery.created_at), sender: delivery.sender
	end
	
end

app/views/email_deliveries/_edit_form.html.haml
= simple_form_for @email_delivery, defaults: { input_html: { size: '60' } } do |f|
	= f.error_notification
	= f.input :recipient, required: true
	= f.input :sender
	= f.input :email_type
	= f.button :submit
	- if @email_delivery.new_record?
		= link_to t('views.cancel'), email_deliveries_path
	- else
		= link_to t('views.done'), email_delivery_path(@email_delivery)
		|
		= link_to 'List', email_deliveries_path

app/views/email_deliveries/edit.html.haml
.edit
	= render partial: 'shared/nav_title', locals: { title: t('views.email_delivery.edit.title', recipient: @email_delivery.recipient) }
	%p#notice= notice
	
	#forms
		= render partial: 'edit_form'
		- if can?(:destroy, @email_delivery)
			= form_for @email_delivery, method: :delete, html: {id: 'destroy_email_delivery', class: 'destroy_button'} do |f|
				= f.submit t('views.email_delivery.edit.destroy_button'), data: { disable_with: t('views.email_delivery.edit.destroy_button_disable'), confirm: t('views.email_delivery.edit.destroy_confirm') }
= render partial: 'shared/save_changes_prompt'

app/views/email_deliveries/index.html.haml
- @page_title = "#{company_name} - #{t('views.email_delivery.name').pluralize}"
.index
	%h1= t('views.email_delivery.name').pluralize
	#top_bar
		= render partial: 'home/admin_nav'
	.email_delivery_nav
		= link_to t('views.email_delivery.edit.create'), new_email_delivery_path
		|
		= link_to t('views.email_delivery.edit.new_list'), new_list_email_deliveries_path
	.list{align: 'center'}
		.pagination_nav
			= render partial: 'shared/per_page_form', locals: { record_type: EmailDelivery }
			= paginate @email_deliveries
		%table
			%thead
				%tr
					%th= EmailDelivery.human_attribute_name :recipient
					%th.large
						= t 'views.email_delivery.view.opt_out_links'
					%th.large
						= EmailDelivery.human_attribute_name :contact_blockers
					%th= EmailDelivery.human_attribute_name :profile
					%th= EmailDelivery.human_attribute_name :sender
					%th= EmailDelivery.human_attribute_name :email_type
					%th= EmailDelivery.human_attribute_name :created_at
					%th= EmailDelivery.human_attribute_name :tracking_category
			%tbody
				- @email_deliveries.each do |email_delivery|
					%tr
						%td= link_to email_delivery.recipient, email_delivery_path(email_delivery)
						%td.select_to_copy
							- if email_delivery.token.present?
								%textarea.ui-corner-all.ui-widget-content{readonly: 'readonly'}
									= new_contact_blocker_from_email_delivery_url email_delivery_token: email_delivery.token
							- else
								%textarea.ui-corner-all.ui-widget-content{readonly: 'readonly'}
									= new_contact_blocker_from_email_address_url e: email_delivery.recipient
						%td
							- email_delivery.contact_blockers.order(:id).each do |record|
								= link_to record.email, contact_blocker_path(record)
						%td= link_to email_delivery.profile.display_name_otherwise_company, profile_path(email_delivery.profile) if email_delivery.profile
						%td= email_delivery.sender
						%td= email_delivery.email_type
						%td= email_delivery.created_at
						%td= email_delivery.tracking_category
		= paginate @email_deliveries
	.email_delivery_nav
		= link_to t('views.email_delivery.edit.create'), new_email_delivery_path
		|
		= link_to t('views.email_delivery.edit.new_list'), new_list_email_deliveries_path

:coffeescript
	$('.select_to_copy textarea').on 'click', ->
		$(this).select()

app/views/email_deliveries/new.html.haml
.edit
	= render partial: 'shared/nav_title', locals: { title: t('views.email_delivery.edit.create') }
	%p#notice= notice
	
	#forms
		= render partial: 'edit_form'
= render partial: 'shared/save_changes_prompt'

app/views/email_deliveries/new_list.html.haml
.edit
	= render partial: 'shared/nav_title', locals: { title: t('views.email_delivery.edit.create_list_title') }
	%p#alert= @alert
	
	#forms
		= form_tag create_list_email_deliveries_path, class: 'simple_form' do
			.input.string.optional
				= label_tag :sender, EmailDelivery.human_attribute_name(:sender), class: 'string optional control-label'
				= text_field_tag :sender, @sender, size: '60', class: 'string optional'
			.input.string.optional
				= label_tag :email_type, EmailDelivery.human_attribute_name(:email_type), class: 'string optional control-label'
				= text_field_tag :email_type, @email_type, size: '60', class: 'string optional'
			.input.string.required
				= label_tag :email_list, t('views.email_delivery.edit.email_list'), class: 'string required control-label'
				= text_area_tag :email_list, @email_list, size: '60x24', placeholder: t('views.email_delivery.edit.email_list_tip'), class: 'string required'
			= submit_tag t('views.email_delivery.edit.create_list'), class: 'btn'
			= link_to t('views.cancel'), email_deliveries_path
	
= render partial: 'shared/save_changes_prompt'

app/views/email_deliveries/show.html.haml
.show
	= render partial: 'shared/nav_title', locals: { title: t('views.email_delivery.view.title', recipient: @email_delivery.recipient) }
	%p#notice= notice
	%table
		%tr
			%td= EmailDelivery.human_attribute_name :recipient
			%td= @email_delivery.recipient
		%tr
			%td= t 'views.email_delivery.view.opt_out_links'
			%td.select_to_copy
				- if @email_delivery.token.present?
					%textarea.ui-corner-all.ui-widget-content{readonly: 'readonly'}
						= new_contact_blocker_from_email_delivery_url email_delivery_token: @email_delivery.token
				- else
					%textarea.ui-corner-all.ui-widget-content{readonly: 'readonly'}
						= new_contact_blocker_from_email_address_url e: @email_delivery.recipient
		%tr
			%td= EmailDelivery.human_attribute_name :contact_blockers
			%td
				- @email_delivery.contact_blockers.order(:id).each do |record|
					= link_to record.email, contact_blocker_path(record)
					%br
		%tr
			%td= EmailDelivery.human_attribute_name :profile
			%td= link_to @email_delivery.profile.display_name_otherwise_company, profile_path(@email_delivery.profile) if @email_delivery.profile
		%tr
			%td= EmailDelivery.human_attribute_name :sender
			%td= @email_delivery.sender
		%tr
			%td= EmailDelivery.human_attribute_name :email_type
			%td= @email_delivery.email_type
		%tr
			%td= EmailDelivery.human_attribute_name :created_at
			%td= @email_delivery.created_at
		%tr
			%td= EmailDelivery.human_attribute_name :tracking_category
			%td= @email_delivery.tracking_category
		%tr
			%td= EmailDelivery.human_attribute_name :token
			%td= @email_delivery.token
	= link_to 'Edit', edit_email_delivery_path(@email_delivery)
	|
	= link_to 'List', email_deliveries_path
	|
	= link_to t('views.email_delivery.edit.create'), new_email_delivery_path

:coffeescript
	$('.select_to_copy textarea').on 'click', ->
		$(this).select()

app/views/email_deliveries/show_list.html.haml
.show
	= render partial: 'shared/nav_title', locals: { title: t('views.email_delivery.view.email_unsubscribe_list_title') }
	%p#notice= @notice
	- if @create_list.email_deliveries.present?
		%p= t 'views.email_delivery.view.email_unsubscribe_list_tip_html'
	%table
		%tr
			%td= t 'views.email_delivery.view.email_unsubscribe_list'
			%td.select_to_copy
				%textarea.ui-widget-content{readonly: 'readonly', rows: '10', cols: '80'}
					= @email_unsubscribe_list
		- if @blocked_recipients.present?
			%tr
				%td= t 'views.email_delivery.view.blocked_recipients'
				%td.select_to_copy
					%textarea.ui-widget-content{readonly: 'readonly'}
						= @blocked_recipients
	%br
	= link_to t('views.email_delivery.edit.new_list'), new_list_email_deliveries_path
	|
	= link_to t('views.email_delivery.view.list'), email_deliveries_path
	|
	= link_to t('views.email_delivery.edit.create'), new_email_delivery_path

:coffeescript
	$('.select_to_copy textarea').on 'click', ->
		$(this).select()