config/routes.rb
Rails.application.routes.draw do
	
	root :to => 'home#index'
	
	get 'about' => 'home#about'
	get 'contact' => 'home#contact'
	get 'terms' => 'home#terms'
	get 'privacy' => 'home#privacy'
	get 'admin' => 'home#admin'
	get 'show_all_categories' => 'home#show_all_categories'
	get 'blog' => 'home#blog'
	get 'pro' => 'home#pro'
	get 'recent_newsletters' => 'home#recent_newsletters'
	get 'newsletter/latest/:name' => 'newsletters#latest', as: :latest_newsletter
	get 'newsletter/list(/:name)' => 'newsletters#list', as: :newsletter_list
	get 'newsletter/:id' => 'newsletters#show',  as: :newsletter
	get 'newsletter' => 'newsletters#new'
	get 'newsletters' => 'newsletters#new'
	get 'newsletters/subscribed' => 'newsletters#subscribed'
	post 'newsletters/subscribe' => 'newsletters#subscribe'
	get 'oldnewsletters' => 'newsletters#new', oldnewsletters: true
	get 'kidnote' => 'newsletters#new', alerts: true
	get 'kidnotes' => 'newsletters#new', alerts: true, as: :alerts
	get 'kidnotes/subscribed' => 'newsletters#subscribed', alerts: true, as: :alerts_subscribed
	post 'kidnotes/subscribe' => 'newsletters#subscribe', alerts: true, as: :alerts_subscribe
	
	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions', 
		confirmations: 'users/confirmations',
		two_factor_authentication: 'users/two_factor_authentication',
		omniauth_callbacks: 'omniauth_callbacks'
	}
	
	devise_scope :user do
		get '/provider/sign_up', to: 'users/registrations#new', is_provider: true
		get '/member/sign_up', to: 'users/registrations#new', is_provider: false
		get '/member/sign_up_return', to: 'users/registrations#new', is_provider: false, store_referrer: true
		get '/member/awaiting_confirmation', to: 'users/registrations#awaiting_confirmation'
		get '/member/sign_in_return', to: 'devise/sessions#new', store_referrer: true
		get '/alpha/sign_up', to: 'users/registrations#new', is_private_alpha: true
		get '/newsletter', to: 'users/registrations#new', nlsub: 't', as: :newsletter_signup
		get '/newsletters', to: 'users/registrations#new', nlsub: 't'
		get '/in_blog/sign_up', to: 'users/registrations#new', blog: true, nlsub: true, in_blog: true
		get '/in_blog/awaiting_confirmation', to: 'users/registrations#in_blog_awaiting_confirmation', in_blog: true
		get '/in_blog/edit_subscriptions', to: 'users/registrations#in_blog_edit_subscriptions', in_blog: true
		get 'two_factor_authentication/qrcode', to: 'users/two_factor_authentication#qrcode'
		get 'two_factor_authentication/reset_code', to: 'users/two_factor_authentication#reset_code'
	end
	
	get 'edit_subscriptions' => 'users#edit_subscriptions', as: 'edit_subscriptions'
	patch 'update_subscriptions' => 'users#update_subscriptions'
	
	
	get 'claim_profile/:token' => 'users#claim_profile', as: :claim_user_profile
	get 'claim_profile/:token/confirm' => 'users#force_claim_profile', as: :force_claim_user_profile
	
	resources :users, only: [:index, :show] do
		member do
			patch 'update_profile_help'
			patch 'formlet_update'
		end
	end
	
	resources :profiles do
		member do
			get 'new_invitation'
			patch 'send_invitation'
			get 'rating_score'
			get 'edit_rating'
			get 'rate'
			post 'rate'
			patch 'formlet_update'
			post 'photo_update'
			get 'show_plain'
			get 'edit_plain'
			get 'claim/:token', action: :show_claiming, as: :show_claiming
			get 'services_info'
			get 'show_tab'
			get 'edit_tab'
			get 'about_payments'
		end
		collection do
			get :admin
			get 'page/:page', action: :index
			get :autocomplete_service_name
			get :autocomplete_specialty_name
			get :autocomplete_location_city
			get :autocomplete_profile_lead_generator
			get :no_categories
			get :no_subcategories
			get :no_services
			get :location_country_data
		end
	end
	
	get 'my_profile' => 'profiles#view_my_profile'
	get 'confirm_claim_profile/:claim_token' => 'profiles#view_my_profile', as: :confirm_claim_profile
	get 'edit_my_profile' => 'profiles#edit_my_profile'
	
	get 'providers' => 'profiles#link_index'
	get 'providers/page/:page' => 'profiles#link_index'
	
	get 'search_providers' => 'profiles#search'
	get 'search_providers/service/:service_id' => 'profiles#search', as: :search_providers_by_service
	get 'search_providers/service/:service_id/page/:page' => 'profiles#search'
	
	resources :categories, except: :show do
		member do
			patch :add_subcategory
			patch :update_subcategory
			patch :remove_subcategory
		end
		collection do
			get :autocomplete_subcategory_name
		end
	end
	
	resources :subcategories, except: :show do
		member do
			patch :add_service
			patch :update_service
			patch :remove_service
		end
		collection do
			get :find_by_name
			get :autocomplete_service_name
		end
	end
	
	resources :services, except: :show do
		get :find_by_name, on: :collection
	end
	
	resources :specialties, except: :show do
		collection do
			get :find_by_name
			get :autocomplete_search_term_name
		end
	end
	
	resources :reviews, except: [:new, :index] do
		member do
			patch :admin_update
		end
		collection do
			post :admin_create
		end
	end
	get 'review/:profile_id' => 'reviews#new', as: :new_review_for_profile
	post 'review/:profile_id'     => 'reviews#create', as: :save_review_for_profile
	
	resources :provider_suggestions

	resources :profile_claims
	get 'profile_claim/:profile_id' => 'profile_claims#new', as: :new_claim_for_profile
	
	resources :contact_blockers
	get 'noemail/:email_delivery_token' => 'contact_blockers#new_from_email_delivery', as: :new_contact_blocker_from_email_delivery
	post 'noemail/:email_delivery_token' => 'contact_blockers#create_from_email_delivery', as: :create_contact_blocker_from_email_delivery
	get 'noemailerror' => 'contact_blockers#email_delivery_not_found', as: :email_delivery_not_found
	get 'noemailconfirmation' => 'contact_blockers#contact_blocker_confirmation', as: :contact_blocker_confirmation
	get 'optout' => 'contact_blockers#new_from_email_address', as: :new_contact_blocker_from_email_address
	post 'optout' => 'contact_blockers#create_from_email_address', as: :create_contact_blocker_from_email_address
	patch 'optout' => 'contact_blockers#create_from_email_address'
	
	post 'magenta/:provider_id' => 'stripe#webhook'
	mount StripeEvent::Engine => '/cyan'

	match 'hooks/a11d83adba52b483798f5e7de90c3e57' => 'mailchimp_webhook#process_notification', via: [:get, :post]

	resources :customers
	get 'authorize_payment/:profile_id' => 'customers#authorize_payment', as: :authorize_payment
	get 'authorize_payment_confirmation/:profile_id' => 'customers#authorize_payment_confirmation', as: :authorize_payment_confirmation
	resources :customer_files, only: [:index, :show] do
		member do
			get :new_charge
			patch :create_charge
		end
	end
	
	resources :stripe_charges, only: :show do
		member do
			patch :create_refund
			get :show_to_client
		end
	end
	
	resources :story_teasers do
		member do
			patch :activate
			patch :deactivate
		end
	end
	
	resources :email_deliveries do
		collection do
			get :new_list
			post :create_list
		end
	end
	
	match '*undefined_path' => 'application#not_found', via: :all
	

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	has_paper_trail # Track changes to each subcategory.
	
	DEFAULT_ACCESSIBLE_ATTRIBUTES = [ :name, :service_ids ]
	
	# Strip leading and trailing whitespace from (admin) input intended for these attributes.
	auto_strip_attributes :name
	
	has_and_belongs_to_many :profiles
	
	has_many :category_subcategories
	has_many :categories, through: :category_subcategories
	
	has_many :service_subcategories do
		def for_service(service)
			where service_id: service
		end
	end
	has_many :services, through: :service_subcategories, after_add: :services_changed, after_remove: :services_changed do
		def by_display_order
			order(ServiceSubcategory.table_name + '.service_display_order')
		end
	end

	# has_and_belongs_to_many :services, after_add: :services_changed, after_remove: :services_changed
	
	default_scope { where(trash: false) }
	scope :trash, -> { rewhere(trash: true) }
	# scope :predefined, -> { where(is_predefined: true) }
	scope :order_by_name, -> { order('lower(name)') }
	
	MAX_STRING_LENGTH = 254
	
	validates :name, presence: true
	validates :name, length: {maximum: MAX_STRING_LENGTH}
	
	paginates_per 20 # Default number shown per page in index listing.
	
	after_save :notify_categories
	
	include CachingForModel
	
	include SunspotIndexing
	
	def service_subcategory(service)
		service_subcategories.for_service(service).first if service
	end
	
	def is_predefined
		true
	end
	
	def browsable?
		categories.any? &:browsable?
	end

	def services_changed(service)
		notify_categories
	end
	
	# Services that are eligible to be assigned to this subcategory.
	# Includes services that are already assigned even if they are not predefined.
	# def assignable_services
	# 	(Service.predefined + services).sort_by(&:lower_case_name).uniq
	# end
	
	# Array of this subcategory's services to be displayed on the home page, sorted by display_order, then name.
	# def services_for_home_page
	# 	services.by_display_order.order_by_name
	# end

	private

	def notify_categories
		categories.each { |category| category.subcategories_changed self }
	end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
	layout 'plain'
	
	before_action :authenticate_user!
	
	# @subcategory and @subcategories initialized by load_and_authorize_resource with cancan ability conditions.
	load_and_authorize_resource
	skip_load_resource only: :autocomplete_service_name
	
	# This is dependent on @subcategory (the resource) being loaded.
	before_action :load_subcategory_service, only: [:update_service, :remove_service]
	
	# Autocomplete service names.
	autocomplete :service, :name, full: true
	
	def index
		@subcategories = @subcategories.order_by_name.page(params[:page]).per(params[:per_page])
	end
	
	# def new
	# end
	
	def create
		if @subcategory.save
			set_flash_message :notice, :created, name: @subcategory.name
			redirect_to edit_subcategory_path(@subcategory)
		else
			set_flash_message :alert, :create_error
			render action: :new
		end
	end
	
	def update
		if @subcategory.update_attributes(subcategory_params)
			set_flash_message :notice, :updated, name: @subcategory.name
			redirect_to edit_subcategory_path(@subcategory)
		else
			set_flash_message :alert, :update_error
			render action: :edit
		end
	end
	
	def destroy
		@subcategory.trash = true
		if @subcategory.save
			set_flash_message :notice, :destroyed, name: @subcategory.name
			redirect_to subcategories_url
		else
			set_flash_message :alert, :destroy_error
			render action: :edit
		end
	end
	
	def add_service
		if (name = params[:name]).present? and (service = name.to_service) and (! @subcategory.services.include?(service))
			# Add service.
			@subcategory.services << service
			set_flash_message :notice, :add_service_success, name: service.name
			# Set display order.
			service_subcategory = @subcategory.service_subcategory(service)
			service_subcategory.service_display_order = params[:service_display_order]
			unless service_subcategory.save
				set_flash_message :alert, :service_display_order_error, name: service.name
			end
		else
			set_flash_message :alert, :add_service_error, name: name
		end
		redirect_to edit_subcategory_path(@subcategory)
	end
	
	def update_service
		if @subcategory.service_subcategory(@service).try(:update_attributes, service_display_order: params[:service_display_order])
			set_flash_message :notice, :update_service_success, name: @service.name
		else
			set_flash_message :alert, :update_service_error
		end
		redirect_to edit_subcategory_path(@subcategory)
	end
	
	def remove_service
		if @service
			@subcategory.services.delete @service
			set_flash_message :notice, :remove_service_success, name: @service.name
		else
			set_flash_message :alert, :remove_service_error
		end
		redirect_to edit_subcategory_path(@subcategory)
	end
	
	def find_by_name
		name = params[:name]
		if name.present? && (subcategory = Subcategory.find_by_name name)
			redirect_to edit_subcategory_path(subcategory)
		else
			set_flash_message :alert, :not_found_by_name, name: name
			redirect_to subcategories_url
		end
	end
	
	private
	
	def load_subcategory_service
		if (service_id = params[:service_id]).present? and (service = Service.find(service_id)) and (@subcategory.services.include?(service))
			@service = service
		end
	end
	
	# Use this method to whitelist the permissible parameters. Example:
	# params.require(:person).permit(:name, :age)
	# Also, you can specialize this method with per-user checking of permissible attributes.
	def subcategory_params
		params.require(:subcategory).permit(*Subcategory::DEFAULT_ACCESSIBLE_ATTRIBUTES)
	end
end

app/views/subcategories/_edit_form.html.haml
= simple_form_for @subcategory do |f|
	= f.input :name, required: true
	-# = f.association :services, as: :check_boxes, collection: @subcategory.assignable_services
	= f.button :submit
	= link_to t('views.cancel'), subcategories_path

app/views/subcategories/edit.html.haml
- @page_title = "#{company_name} - #{t('views.subcategory.edit.edit')} '#{@subcategory.name}'"
.edit
	%h1= "#{t('views.subcategory.edit.edit')} '#{@subcategory.name}'"
	#top_bar
		= render partial: 'home/admin_nav'
	#forms
		= render partial: 'edit_form'
		- if can?(:destroy, @subcategory)
			= form_for @subcategory, method: :delete, html: {id: 'destroy_subcategory', class: 'destroy_button'} do |f|
				= f.submit t('views.subcategory.edit.destroy_button'), data: { disable_with: t('views.category.edit.destroy_button_disable'), confirm: t('views.subcategory.edit.destroy_confirm') }
	#links
		%a{name: 'links'}
		%h1= Subcategory.human_attribute_name :categories
		%ul
			- if @subcategory.categories.present?
				- @subcategory.categories.home_page_order.each do |record|
					%li= link_to record.name, edit_category_path(record), class: 'name'
			- else
				%li= link_to t('views.subcategory.edit.add_categories'), categories_path
		%h1= Subcategory.human_attribute_name :services
		- if @subcategory.services.present?
			%table
				%thead
					%tr
						%th.miniform_header
							= Service.human_attribute_name(:display_order)
						%th= t 'views.service.edit.edit'
						%th
				%tbody
					- @subcategory.services.by_display_order.order_by_name.each do |record|
						%tr
							%td.miniform
								= form_for @subcategory, url: {action: :update_service} do |f|
									= f.submit t('views.save'), data: { disable_with: t('views.saving') }
									= text_field_tag :service_display_order, @subcategory.service_subcategory(record).service_display_order, size: 4
									= hidden_field_tag :service_id, record.to_param
							%td= link_to record.name, edit_service_path(record), class: 'name'
							%td.miniform
								= form_for @subcategory, url: {action: :remove_service} do |f|
									= f.submit t('views.remove'), data: { disable_with: t('views.removing') }
									= hidden_field_tag :service_id, record.to_param
		%h1= t 'views.service.edit.add'
		%table
			%thead
				%tr
					%th.miniform_header
						= Service.human_attribute_name(:display_order)
						&nbsp;&nbsp;
						= t 'views.service.name'
			%tbody
				%tr
					%td.miniform
						= form_for @subcategory, url: {action: :add_service} do |f|
							= f.submit t('views.save'), data: { disable_with: t('views.saving') }
							= text_field_tag :service_display_order, '', size: 4
							= autocomplete_form_field :name, '', autocomplete_service_name_subcategories_path, placeholder: t('views.service.view.find_by_name'), size: 30
= render partial: 'shared/save_changes_prompt'

app/views/subcategories/index.html.haml
- @page_title = "#{company_name} - #{t('views.subcategory.name').pluralize}"
.index
	%h1= t('views.subcategory.name').pluralize
	#top_bar
		= render partial: 'home/admin_nav'
	.list{align: 'center'}
		= form_tag find_by_name_subcategories_path, method: :get do
			= submit_tag t('views.find_button'), data: { disable_with: 'Finding...' }
			= autocomplete_form_field 'name', '', autocomplete_subcategory_name_categories_path, placeholder: t('views.subcategory.view.find_by_name'), size: 50
		.pagination_nav
			= render partial: 'shared/per_page_form', locals: { record_type: Subcategory }
			= paginate @subcategories
		%table
			%thead
				%tr
					%th
						= t 'views.subcategory.name'
						-# %br
						-# = t 'views.not_browsable'
					%th.large
						= Subcategory.human_attribute_name(:services)
						-# %br
						-# = t 'views.subcategory.index.service_explanation'
					%th.large= Subcategory.human_attribute_name(:categories).singularize
			%tbody
				- @subcategories.each do |subcategory|
					%tr
						%td= link_to subcategory.name, edit_subcategory_path(subcategory), class: "#{subcategory.browsable? ? 'browsable' : 'not_browsable'}"
						%td
							- subcategory.services.by_display_order.order_by_name.each do |record|
								= link_to record.name, edit_service_path(record), class: "name #{record.browsable? ? 'browsable' : 'not_browsable'}"
						%td
							- subcategory.categories.order_by_name.each do |record|
								= link_to record.name, edit_category_path(record), class: "name #{record.browsable? ? 'browsable' : 'not_browsable'}"
		.pagination_nav
			= render partial: 'shared/per_page_form', locals: { record_type: Subcategory }
			= paginate @subcategories

app/views/subcategories/new.html.haml
- @page_title = "#{company_name} - #{t('views.subcategory.edit.create')}"
.edit
	%h1= t('views.subcategory.edit.create')
	#top_bar
		= render partial: 'home/admin_nav'
	#forms
		= render partial: 'edit_form'
= render partial: 'shared/save_changes_prompt'