config/routes.rb
Rails.application.routes.draw do
	
	root :to => 'home#index'
	
	get 'about' => 'home#about'
	get 'contact' => 'home#contact'
	get 'terms' => 'home#terms'
	get 'privacy' => 'home#privacy'
	get 'admin' => 'home#admin'
	get 'show_all_categories' => 'home#show_all_categories'
	get 'blog' => 'home#blog'
	get 'pro' => 'home#pro'
	get 'recent_newsletters' => 'home#recent_newsletters'
	get 'newsletter/latest/:name' => 'newsletters#latest', as: :latest_newsletter
	get 'newsletter/list(/:name)' => 'newsletters#list', as: :newsletter_list
	get 'newsletter/:id' => 'newsletters#show',  as: :newsletter
	get 'newsletter' => 'newsletters#new'
	get 'newsletters' => 'newsletters#new'
	get 'newsletters/subscribed' => 'newsletters#subscribed'
	post 'newsletters/subscribe' => 'newsletters#subscribe'
	get 'oldnewsletters' => 'newsletters#new', oldnewsletters: true
	get 'kidnote' => 'newsletters#new', alerts: true
	get 'kidnotes' => 'newsletters#new', alerts: true, as: :alerts
	get 'kidnotes/subscribed' => 'newsletters#subscribed', alerts: true, as: :alerts_subscribed
	post 'kidnotes/subscribe' => 'newsletters#subscribe', alerts: true, as: :alerts_subscribe
	
	devise_for :users, controllers: { 
		registrations: 'users/registrations', 
		sessions: 'users/sessions', 
		confirmations: 'users/confirmations',
		two_factor_authentication: 'users/two_factor_authentication',
		omniauth_callbacks: 'omniauth_callbacks'
	}
	
	devise_scope :user do
		get '/provider/sign_up', to: 'users/registrations#new', is_provider: true
		get '/member/sign_up', to: 'users/registrations#new', is_provider: false
		get '/member/sign_up_return', to: 'users/registrations#new', is_provider: false, store_referrer: true
		get '/member/awaiting_confirmation', to: 'users/registrations#awaiting_confirmation'
		get '/member/sign_in_return', to: 'devise/sessions#new', store_referrer: true
		get '/alpha/sign_up', to: 'users/registrations#new', is_private_alpha: true
		get '/newsletter', to: 'users/registrations#new', nlsub: 't', as: :newsletter_signup
		get '/newsletters', to: 'users/registrations#new', nlsub: 't'
		get '/in_blog/sign_up', to: 'users/registrations#new', blog: true, nlsub: true, in_blog: true
		get '/in_blog/awaiting_confirmation', to: 'users/registrations#in_blog_awaiting_confirmation', in_blog: true
		get '/in_blog/edit_subscriptions', to: 'users/registrations#in_blog_edit_subscriptions', in_blog: true
		get 'two_factor_authentication/qrcode', to: 'users/two_factor_authentication#qrcode'
		get 'two_factor_authentication/reset_code', to: 'users/two_factor_authentication#reset_code'
	end
	
	get 'edit_subscriptions' => 'users#edit_subscriptions', as: 'edit_subscriptions'
	patch 'update_subscriptions' => 'users#update_subscriptions'
	
	
	get 'claim_profile/:token' => 'users#claim_profile', as: :claim_user_profile
	get 'claim_profile/:token/confirm' => 'users#force_claim_profile', as: :force_claim_user_profile
	
	resources :users, only: [:index, :show] do
		member do
			patch 'update_profile_help'
			patch 'formlet_update'
		end
	end
	
	resources :profiles do
		member do
			get 'new_invitation'
			patch 'send_invitation'
			get 'rating_score'
			get 'edit_rating'
			get 'rate'
			post 'rate'
			patch 'formlet_update'
			post 'photo_update'
			get 'show_plain'
			get 'edit_plain'
			get 'claim/:token', action: :show_claiming, as: :show_claiming
			get 'services_info'
			get 'show_tab'
			get 'edit_tab'
			get 'about_payments'
		end
		collection do
			get :admin
			get 'page/:page', action: :index
			get :autocomplete_service_name
			get :autocomplete_specialty_name
			get :autocomplete_location_city
			get :autocomplete_profile_lead_generator
			get :no_categories
			get :no_subcategories
			get :no_services
			get :location_country_data
		end
	end
	
	get 'my_profile' => 'profiles#view_my_profile'
	get 'confirm_claim_profile/:claim_token' => 'profiles#view_my_profile', as: :confirm_claim_profile
	get 'edit_my_profile' => 'profiles#edit_my_profile'
	
	get 'providers' => 'profiles#link_index'
	get 'providers/page/:page' => 'profiles#link_index'
	
	get 'search_providers' => 'profiles#search'
	get 'search_providers/service/:service_id' => 'profiles#search', as: :search_providers_by_service
	get 'search_providers/service/:service_id/page/:page' => 'profiles#search'
	
	resources :categories, except: :show do
		member do
			patch :add_subcategory
			patch :update_subcategory
			patch :remove_subcategory
		end
		collection do
			get :autocomplete_subcategory_name
		end
	end
	
	resources :subcategories, except: :show do
		member do
			patch :add_service
			patch :update_service
			patch :remove_service
		end
		collection do
			get :find_by_name
			get :autocomplete_service_name
		end
	end
	
	resources :services, except: :show do
		get :find_by_name, on: :collection
	end
	
	resources :specialties, except: :show do
		collection do
			get :find_by_name
			get :autocomplete_search_term_name
		end
	end
	
	resources :reviews, except: [:new, :index] do
		member do
			patch :admin_update
		end
		collection do
			post :admin_create
		end
	end
	get 'review/:profile_id' => 'reviews#new', as: :new_review_for_profile
	post 'review/:profile_id'     => 'reviews#create', as: :save_review_for_profile
	
	resources :provider_suggestions

	resources :profile_claims
	get 'profile_claim/:profile_id' => 'profile_claims#new', as: :new_claim_for_profile
	
	resources :contact_blockers
	get 'noemail/:email_delivery_token' => 'contact_blockers#new_from_email_delivery', as: :new_contact_blocker_from_email_delivery
	post 'noemail/:email_delivery_token' => 'contact_blockers#create_from_email_delivery', as: :create_contact_blocker_from_email_delivery
	get 'noemailerror' => 'contact_blockers#email_delivery_not_found', as: :email_delivery_not_found
	get 'noemailconfirmation' => 'contact_blockers#contact_blocker_confirmation', as: :contact_blocker_confirmation
	get 'optout' => 'contact_blockers#new_from_email_address', as: :new_contact_blocker_from_email_address
	post 'optout' => 'contact_blockers#create_from_email_address', as: :create_contact_blocker_from_email_address
	patch 'optout' => 'contact_blockers#create_from_email_address'
	
	post 'magenta/:provider_id' => 'stripe#webhook'
	mount StripeEvent::Engine => '/cyan'

	match 'hooks/a11d83adba52b483798f5e7de90c3e57' => 'mailchimp_webhook#process_notification', via: [:get, :post]

	resources :customers
	get 'authorize_payment/:profile_id' => 'customers#authorize_payment', as: :authorize_payment
	get 'authorize_payment_confirmation/:profile_id' => 'customers#authorize_payment_confirmation', as: :authorize_payment_confirmation
	resources :customer_files, only: [:index, :show] do
		member do
			get :new_charge
			patch :create_charge
		end
	end
	
	resources :stripe_charges, only: :show do
		member do
			patch :create_refund
			get :show_to_client
		end
	end
	
	resources :story_teasers do
		member do
			patch :activate
			patch :deactivate
		end
	end
	
	resources :email_deliveries do
		collection do
			get :new_list
			post :create_list
		end
	end
	
	match '*undefined_path' => 'application#not_found', via: :all
	

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
	has_paper_trail # Track changes to each rating.
	
	# attr_accessible :cid, :list_id, :send_time, :title, :subject, :archive_url, :content
	validates_presence_of :cid, :list_id, :send_time, :title, :subject, :archive_url, :content
	
	scope :parent_newsletters, -> { where(
		"list_id = '#{mailchimp_list_ids[:parent_newsletters]}' AND title NOT LIKE 'Kids 0-4%'")
	}
	scope :parent_newsletters_stage1, -> { where(
		"list_id = '#{mailchimp_list_ids[:parent_newsletters_stage1]}' OR
		(list_id = '#{mailchimp_list_ids[:parent_newsletters]}' AND 
		title LIKE 'Kids 0-4%')")
	}
	scope :parent_newsletters_stage2, -> { where(
		"list_id = '#{mailchimp_list_ids[:parent_newsletters_stage2]}' OR
		(list_id = '#{mailchimp_list_ids[:parent_newsletters]}' AND 
		title LIKE 'Kids 5-12%')")
	}
	scope :parent_newsletters_stage3, -> { where(
		"list_id = '#{mailchimp_list_ids[:parent_newsletters_stage3]}' OR
		(list_id = '#{mailchimp_list_ids[:parent_newsletters]}' AND 
		title LIKE 'Teens%')")
	}
	
	def self.order_by_send_time
		order('send_time desc')
	end
	
	def self.last_updated
		order(:updated_at).last
	end

	def self.last_sent
		order(:send_time).last
	end
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
	
	respond_to :html
	
	before_action :load_variables

	# GET /newsletter
	def new
		if @subscribing_to_alerts or @subscribing_to_oldnewsletters
			render layout: 'interior'
		else
			redirect_to alerts_url
		end
	end

	# POST /newsletters/subscribe
	def subscribe
		@errors = []
		@email = params[:email].presence
		@duebirth1 = params[:duebirth1].presence
		
		active_mailing_lists.each do |list|
			instance_variable_set "@#{list}", params[list].present?
		end

		subscribe_lists = active_mailing_lists.select do |list|
			instance_variable_get "@#{list}"
		end

		@errors << t('views.newsletter.email_required') if @email.blank?
		@errors << t('views.newsletter.list_required') if subscribe_lists.blank?
		@errors << t('views.newsletter.bad_date_format', input_format: input_date_format_string) if @duebirth1 && @duebirth1 !~ input_date_regexp && @duebirth1 !~ iso_date_regexp

		if @errors.any?
			render :new
		else
			subscribe_options = {
				subscribing_to_alerts: @subscribing_to_alerts,
				merge_vars: { 'SUBSOURCE' => 'directory_subscription_page' }
			}
			subscribe_options[:merge_vars]['DUEBIRTH1'] = @duebirth1 if @duebirth1
			job = NewsletterSubscriptionJob.new subscribe_lists, @email, subscribe_options
			if update_mailing_lists_in_background?
				Delayed::Job.enqueue job
			else
				job.perform
			end
			subscribed_url_params = subscribe_lists.inject(nlsub: 't'){ |p, list| p.merge list => 't' }
			if @subscribing_to_alerts
				redirect_to alerts_subscribed_url(subscribed_url_params)
			else
				redirect_to newsletters_subscribed_url(subscribed_url_params)
			end
		end
	end

	# GET /newsletters/subscribed
	def subscribed
		render :subscribed, layout: 'interior'
	end

	# GET /latest/:name
	def latest
		name = params[:name]
		@newsletter = case name
			when "parent_newsletters_stage2"
				Newsletter.parent_newsletters_stage2.last_sent
			when "parent_newsletters_stage3"
				Newsletter.parent_newsletters_stage3.last_sent
			else
				Newsletter.parent_newsletters_stage1.last_sent
			end
		@styles = false
		set_seo_elements @newsletter
		render :show, layout: 'iframe_layout'
	end

	# GET /list/:name, where :name is optional
	def list
		name = params[:name]
		list_name = list_name(name)
		@stage1_newsletters = Newsletter.parent_newsletters_stage1.order_by_send_time
		@stage2_newsletters = Newsletter.parent_newsletters_stage2.order_by_send_time
		@stage3_newsletters = Newsletter.parent_newsletters_stage3.order_by_send_time
		@meta_description = "#{t 'views.newsletter.archive'} - #{t 'views.newsletter.name'}"
		@meta_keywords = "#{t 'views.newsletter.archive'} #{t 'views.newsletter.name'}".downcase
	end

	# GET /list/:id
	def show
		id = params[:id]
		@styles = false
		@newsletter = Newsletter.find_by_cid(id)
		set_seo_elements @newsletter
		render layout: 'iframe_layout'
	end

	# Class method to create a new MailChimp subscription.
	def self.subscribe_to_mailing_lists(lists, email, options={})
		successful_subscribes = []
		lists.each do |list_name|
			next if !User.mailing_list_name_valid?(list_name)

			list_id = mailchimp_list_ids[list_name]
			
			begin
				r = Gibbon::Request.lists(list_id).members(email_md5_hash(email)).upsert body: {
					email_address: email,
					status: 'subscribed',
					merge_fields: options[:merge_vars]
				}
				if r.try(:[], 'status') == 'subscribed'
					successful_subscribes << list_name
				end
			rescue Gibbon::MailChimpError => e
				logger.error "MailChimp error while subscribing guest user with email #{email} to #{list_name}: #{e.title}; #{e.detail}; status: #{e.status_code}"
			end
		end
		if successful_subscribes.any?
			if options[:subscribing_to_alerts]
				AdminMailer.alerts_subscribe_alert(successful_subscribes, email, options).deliver_now
			else
				AdminMailer.newsletter_subscribe_alert(successful_subscribes, email).deliver_now
			end
		end
	end
	
	private
	
	def load_variables
		@subscribing_to_alerts = params[:alerts].present?
		@subscribing_to_oldnewsletters = params[:oldnewsletters].present?
	end

	def list_name(name_str)
		case name_str
		when "parent_newsletters_stage1"
			list_name = :parent_newsletters_stage1
		when "parent_newsletters_stage2"
		 	list_name = :parent_newsletters_stage2
		when "parent_newsletters_stage3"
		 	list_name = :parent_newsletters_stage3
		end
		list_name
	end

	def default_sample_url(list_name)
		case list_name
		when :parent_newsletters_stage1
			url = "http://us9.campaign-archive1.com/?u=9da2f83266d2dfd9641ba63f6&id=6d7f820f78"
		when :parent_newsletters_stage2
			url = "http://us9.campaign-archive1.com/?u=9da2f83266d2dfd9641ba63f6&id=2d58b8e01a"
		when :parent_newsletters_stage3
			url = "http://us9.campaign-archive1.com/?u=9da2f83266d2dfd9641ba63f6&id=272d9c40d2"
		else
			url = "#"
		end
		url
	end

	def archive_url(id)
		begin
			r = Gibbon::Request.campaigns(id).retrieve params: {
				fields: 'archive_url'
			}
			url = r.try :[], 'archive_url'
		rescue Gibbon::MailChimpError => e
			logger.info "Error while retrieving MailChimp newsletter campaign ID #{id}: #{e.title}; #{e.detail}; status: #{e.status_code}"
		ensure
			return url
		end
	end

	def latest_archive_url(list_name)
		begin
			list_id = mailchimp_list_ids[list_name]
			
			r = Gibbon::Request.campaigns.retrieve params: {
				list_id: list_id,
				status: 'sent',
				fields: 'campaigns.archive_url'
			}
			url = r.try(:[], 'campaigns').try(:last).try(:[], 'archive_url')
		rescue Gibbon::MailChimpError => e
			logger.info "Error while retrieving latest MailChimp newsletter url for #{list_name}: #{e.title}; #{e.detail}; status: #{e.status_code}"
		ensure
			return url
		end
	end

	def list_archive(list_name)
		begin
			list_id = mailchimp_list_ids[list_name]
			
			r = Gibbon::Request.campaigns.retrieve params: {
				list_id: list_id,
				status: 'sent',
				fields: 'campaigns.archive_url,campaigns.settings.subject_line'
			}
			data = r.try(:[], 'campaigns').try(:reverse).try(:[], 0, 100)
		rescue Gibbon::MailChimpError => e
			logger.info "Error while retrieving MailChimp newsletter urls for #{list_name}: #{e.title}; #{e.detail}; status: #{e.status_code}"
		ensure
			return data || []
		end
	end
	
	# Set instance variables used to populate SEO elements, e.g., meta description and keywords.
	def set_seo_elements(newsletter)
		if newsletter
			@meta_description = "#{t 'views.newsletter.name'} - #{newsletter.subject} - Sent #{newsletter.send_time}"
			@meta_keywords = newsletter.subject.downcase
		end
	end
	
	# Set exceptions to default values of the security-related HTTP headers in the response.
	# See https://www.owasp.org/index.php/List_of_useful_HTTP_headers
	# http://tools.ietf.org/html/rfc7034
	# http://www.w3.org/TR/CSP/#directive-frame-ancestors
	def set_default_response_headers
		super
		if response && ['latest', 'show'].include?(action_name)
			response.headers.merge!({
				'Content-Security-Policy' => "frame-ancestors 'self'",
				'X-Frame-Options' => 'SAMEORIGIN'
			})
		end
	end
end

app/helpers/newsletters_helper.rb
module NewslettersHelper
	def format_newsletter_date(date)
		date.strftime('%B %d, %Y') rescue Time.zone.now.strftime('%B %d, %Y')
	end
	
	def newsletter_link_text(newsletter)
		"#{format_newsletter_date newsletter.send_time}: #{newsletter.subject}"
	end
end

app/views/newsletters/list.html.haml
- @hide_search_providers = true
- @content_class = 'no-upper-hr'
- @page_title_prefix = t 'views.newsletter.archive'
- short_company_description = t 'company.short_company_description_html'

- cache ['newsletter_archive', Newsletter.last_updated, user_signed_in?] do
	.container.newsletter-archive
		%p= link_to t('views.newsletter.sign_up_link'), newsletter_signup_path, {class: 'back-to-signup-link'}
		= image_tag "newsletter_banner.jpg", alt: short_company_description, itemprop: 'image', class: "banner"
		%h1= t 'views.newsletter.archive'
		%ul.mobile-nav
			%li Jump to:
			%li 
				%a{ href: '#col-one'}= User.human_attribute_name :parent_newsletters_stage1
			%li 
				%a{ href: '#col-two'}= User.human_attribute_name :parent_newsletters_stage2
			%li 
				%a{ href: '#col-three'}= User.human_attribute_name :parent_newsletters_stage3
		%article.newsletter-list
			.col.one-third#col-one
				%h3= User.human_attribute_name :parent_newsletters_stage1
				%ul
					- @stage1_newsletters.each do |newsletter|
						%li
							=link_to newsletter_link_text(newsletter), newsletter_path(newsletter.cid), { target: '_blank' }
					- if @stage1_newsletters.empty?
						%li No recent newsletter
			.col.one-third#col-two
				%h3= User.human_attribute_name :parent_newsletters_stage2
				%ul
					- @stage2_newsletters.each do |newsletter|
						%li
							=link_to newsletter_link_text(newsletter), newsletter_path(newsletter.cid), { target: '_blank' }
					- if @stage2_newsletters.empty?
						%li No recent newsletter
			.col.one-third.last#col-three
				%h3= User.human_attribute_name :parent_newsletters_stage3
				%ul
					- @stage3_newsletters.each do |newsletter|
						%li
							=link_to newsletter_link_text(newsletter), newsletter_path(newsletter.cid), { target: '_blank' }
					- if @stage3_newsletters.empty?
						%li No recent newsletter

app/views/newsletters/new.html.haml
- @content_class = 'no-upper-hr full-width'
- @page_title_prefix = t 'views.newsletter.name'
- @hide_masthead = true
- @hide_follow = true
- @og_title = "#{t 'views.newsletter.name'} | #{company_tagline}"
- @og_description = @meta_description = t 'views.newsletter.description'
- short_company_description ||= t 'company.short_company_description_html'
- parent_newsletters_hint	= t "views.sign_up.parent_newsletters_hint"

#login_panel.newsletter-sign-up
	.container.positioner
		.company_desc
			- if @subscribing_to_alerts
				%a{title: "#{company_name}", href: root_url}
					= image_tag 'kidNotes_hed-9.jpg', alt: short_company_description, itemprop: 'image', class: "banner"
				%h5= t 'views.newsletter.description_html'
			- else
				%a{title: "#{company_name}", href: root_url}
					= image_tag 'newsletter_banner.jpg', alt: short_company_description, itemprop: 'image', class: "banner"
				%h5= t 'views.newsletter.description_html'
		#sign_up.generic_form
			= form_tag "/newsletters/subscribe" do
				- unless @errors.blank?
					%p#error_explanation.center
						- @errors.each do |error|
							= error
							%br
				= hidden_field_tag :parent_newsletters, '1'
				- if @subscribing_to_alerts
					= hidden_field_tag :alerts, '1'
					.text_field
						= label_tag :duebirth1, "#{t 'views.newsletter.duebirth1'}:"
						= text_field_tag :duebirth1, @duebirth1, type: 'date', placeholder: input_date_format_string, pattern: input_date_regexp_string
				- else
					= hidden_field_tag :oldnewsletters, '1'
				.email.text_field
					= label_tag :email, 'Email:'
					= email_field_tag :email, @email, placeholder: 'Enter your email address'
				.buttons
					= submit_tag t(:newsletter_sign_up_label, scope: 'views.sign_up'), data: { disable_with: t('views.sign_up.submit_disable') }, class: 'default newsletter_sign_up', id: 'sign_up_button'
					= link_to t(:newsletter_sign_up_cancel, scope: 'views.sign_up'), root_path, class: 'cancel', id: 'sign_up_cancel_button'
		-# %p.newsletter-sample
		-# 	See a sample:
		-# 	=link_to User.human_attribute_name(:parent_newsletters_stage1), '#stage1_sample_view'
		-# 	|
		-# 	=link_to User.human_attribute_name(:parent_newsletters_stage2), '#stage2_sample_view'
		-# 	|
		-# 	=link_to User.human_attribute_name(:parent_newsletters_stage3), '#stage3_sample_view'
		-# 	%span.left-indent
		-# 		Or check out our
		-# 		= succeed '.' do
		-# 			= link_to 'archive', newsletter_list_path
	%section.col2
		%blockquote
			"This is my new favorite email. It actually makes me a better mom."
			%cite—mom of preschooler, now pregnant with #2
		%blockquote
			"What I love about these emails is that they're filled with info on exactly the topics I wonder/worry/want to know more about. Like just this morning's email about what the college wait list really means for my daughter. Perfect timing!"
			%cite—mom of two teen girls
	%section.col2
		%blockquote
			"Wow. It really is a great newsletter."
			%cite—pediatrician and dad of three
		%blockquote
			"I love this newsletter. I always find some gem—it's as if you know exactly what I'm going through with my kids."
			%cite—mom of kids ages 5 and 8
	%hr.clearfix
	.follow
		%h3 Share & Follow Us
		%ul
			%li
				%a.fb{href: "https://www.facebook.com/kinstantly", :target => "_blank"}
					= image_tag "facebook.png", alt: "Facebook", itemprop: 'image', border: "0"
					Facebook
			%li
				%a.tw{href: "https://twitter.com/Kinstantly", :target => "_blank"}
					= image_tag "twitter.png", alt: "Twitter", itemprop: 'image', border: "0"
					Twitter
			%li
				%a.gp{href: "https://plus.google.com/+Kinstantly", :target => "_blank"}
					= image_tag "googleone.png", alt: "Google Plus", itemprop: 'image', border: "0"
					Google Plus
	-# %hr.clearfix
	-# =link_to '^ Back to sign up', '#login_panel', {class: 'back-to-top-link right', id: 'stage1_sample_view'}
	-# %iframe{src: "#{latest_newsletter_url(:parent_newsletters_stage1, noga: 't')}", id: 'stage1_sample', width: '100%', onload: 'my_vars.f.setIframeHeight(this.id)'}
	-# =link_to '^ Back to sign up', '#login_panel', {class: 'back-to-top-link right', id: 'stage2_sample_view'}
	-# %iframe{src: "#{latest_newsletter_url(:parent_newsletters_stage2, noga: 't')}", id: 'stage2_sample', width: '100%', onload: 'my_vars.f.setIframeHeight(this.id)'}
	-# =link_to '^ Back to sign up', '#login_panel', {class: 'back-to-top-link right', id: 'stage3_sample_view'}
	-# %iframe{src: "#{latest_newsletter_url(:parent_newsletters_stage3, noga: 't')}", id: 'stage3_sample', width: '100%', onload: 'my_vars.f.setIframeHeight(this.id)'}
	-# =link_to '^ Back to sign up', '#login_panel', {class: 'back-to-top-link right'}

-# -# The following JavaScript sets the height of the iframe to match its document's height so that the regular window scrollbars can be used rather than iframe scrollbars.
-# -# Source: http://www.dyn-web.com/tutorials/iframes/height/demo.php
-# -# See also: stackoverflow.com/questions/1145850/
-# :javascript
-# 	my_vars.f.getDocHeight = function (doc) {
-# 		doc = doc || document;
-# 		var body = doc.body, html = doc.documentElement;
-# 		var height = Math.max(body.scrollHeight, body.offsetHeight, html.clientHeight, html.scrollHeight, html.offsetHeight);
-# 		return height;
-# 	}
-#
-# 	my_vars.f.setIframeHeight = function (id) {
-# 			var ifrm = document.getElementById(id);
-# 			var doc = ifrm.contentDocument? ifrm.contentDocument: ifrm.contentWindow.document;
-# 			ifrm.style.visibility = 'hidden';
-# 			ifrm.style.height = "10px"; // reset to minimal height ...
-# 			// IE opt. for bing/msn needs a bit added or scrollbar appears
-# 			ifrm.style.height = my_vars.f.getDocHeight(doc) + 4 + "px";
-# 			ifrm.style.visibility = 'visible';
-# 	}

app/views/newsletters/show.html.haml
- if @newsletter
	- @page_title = "#{@newsletter.subject} | #{format_newsletter_date @newsletter.send_time} | #{company_name} | #{company_tagline}"
	= raw @newsletter.content
- else
	.error_panel
		%p= t 'views.page_load_error_message_html', path: request.fullpath

app/views/newsletters/subscribed.html.haml
- @hide_search_providers = true
- embedded_in ||= false
- info_email = "#{t('contact.emails.info.value')}@#{t('email_domain')}"
#content
	#awaiting_confirmation.wider_form
		- if @subscribing_to_alerts
			%p.thank-you THANK YOU!
			%br
			%br
			%p= "You're all signed up for #{t 'views.newsletter.name'}."
			%br
			%p.newsletter-resources
				Can't wait? Check out our
				= link_to 'blog', blog_url
				for inspiring stories and use-it-now parenting advice. Or search our
				= link_to 'directory', root_path
				for amazing parenting experts and family services.
			%br
			%p Welcome to Kinstantly!
			%br
		- else
			%p.thank-you THANK YOU!
			%br
			%br
			%p You're all signed up for Kinstantly This Week.
			%br
			%p Watch your inbox for us each Friday morning.
			%br
			%p.newsletter-resources
				Can't wait? Check out our
				= link_to 'blog', blog_url
				for inspiring stories and use-it-now parenting advice. Or search our
				= link_to 'directory', root_path
				for amazing parenting experts and family services.
			%br
			%p Welcome to Kinstantly!
			%br